import StudentCard from "../../../components/StudentCard/StudentCard";

// students.js
const alumniStudents = [
  {
    name: "Nanduri Sesha Sai Pavan Kalyan",
    image: "Pavan.jpg",
    degree: "M.S. + Ph.D.",
    year: "2019 - 2025",
    isPrimaryGuidePresent: false,
    researchTitle:
      "Discrete–Continuum Modelling of Fracture and Contact in Granular Materials",
    profileLink: "https://pkc137.github.io/sudo_template_website",
    email: "pk90901@hotmail.com",
    // keywords: ["Particle characterization", "µCT", "Contact mechanics"],
    affiliation:
      "Research Associate,  École Polytechnique Fédérale de Lausanne",

    googleSchLink:
      "https://scholar.google.co.in/citations?user=R5rSqzgAAAAJ&hl=en",
    researchGateLink: "https://www.researchgate.net/profile/Nssp-Kalyan",
    linkedinLink: "https://www.linkedin.com/in/n-s-s-p-kalyan-6b5a871a4/",
  },
  {
    name: "Sahil Wani",
    image: "Sahil.png",
    degree: "Ph.D.",
    year: "2020 - 2025",
    isPrimaryGuidePresent: false,
    researchTitle: "Geomechanical modelling of gas hydrate sediments",
    profileLink: "https://sites.google.com/view/sahilwani/",
    email: "shlwn76@gmail.com",
    // keywords: [
    //   "Constitutive behaviour",
    //   "Modelling of geo-materials",
    //   "Boundary value problems",
    // ],
    affiliation: "Research Associate, Peking University",
    googleSchLink:
      "https://scholar.google.co.in/citations?user=JjfrZE8AAAAJ&hl=en",
    researchGateLink: "https://www.researchgate.net/profile/Sahil-Wani",
    linkedinLink: "https://in.linkedin.com/in/sahil-wani",
  },
  {
    name: "Jithin S Kumar",
    image: "jsk.jpg",
    degree: "Ph.D.",
    year: "2019 - 2024",
    researchTitle:
      "Understanding the flow dynamics and deformation characteristics during fluid injection through porous media",
    researchLink: "",
    email: "jithin.jsk@gmail.com",
    keywords: [],
    affiliation: "Well Engineer, ExxonMobil",
    googleSchLink:
      "https://scholar.google.co.in/citations?user=TcJS02cAAAAJ&hl=en",
    researchGateLink: "https://www.researchgate.net/profile/Jithin-Kumar-3",
    linkedinLink: "https://in.linkedin.com/in/jithin-s-kumar-090591b2",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Varshik Baliboyna",
    image: "Varshik.jpeg",
    degree: "M.Tech.",
    year: "2024 - 2026",
    researchTitle: "Scale effect of granular materials",
    researchLink: "",
    email: "ce24m049@smail.iitm.ac.in",
    keywords: [],
    affiliation: "",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/varshik-baliboyna/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Abhinand Valsaraj C",
    image: "Abhinand.jpeg",
    degree: "M.Tech.",
    year: "2024 - 2026",
    researchTitle: "Fragmentation of quasi-brittle materials during impact",
    researchLink: "",
    email: "ce24m034@smail.iitm.ac.in",
    keywords: [],
    affiliation: "",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/abhinand-valsaraj-c-434b7b23b/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "B N Prerana",
    image: "Prerana.jpeg",
    degree: "M.Tech.",
    year: "2023 - 2025",
    researchTitle: "Mechanics of cement treated clay",
    researchLink: "",
    email: "ce23m037@smail.iitm.ac.in",
    keywords: [],
    affiliation: "JLL India",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/b-n-prerana-a2a862216/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Saikiran Naikoti",
    image: "SaiKiran.jpg",
    degree: "M.Tech.",
    year: "2022 - 2024",
    researchTitle:
      "Transition of cavity to finger during fluid injection through granular medium",
    researchLink: "",
    email: "naikotisaikiran22@gmail.com",
    keywords: [],
    affiliation: "Verdantas",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/saikiran-naikoti-eit-080923308/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Megha S Narayanan",
    image: "Megha.jfif",
    degree: "M.Tech.",
    year: "2021 - 2023",
    researchTitle:
      "Numerical modelling of soil–coir geotextile interaction during pullout loading",
    researchLink: "",
    email: "megha19898@gmail.com",
    keywords: [],
    affiliation: "Hamburg University of Technology, Germany",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/megha-s-narayanan-77b33b22b/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Prakash Badu",
    image: "Prakash.jpg",
    degree: "M.Tech.",
    year: "2021 - 2023",
    researchTitle:
      "Micromechanics of aggregate–rubber interactions during simple shear – A DEM study",
    researchLink: "",
    email: "prakash.badu123@gmail.com",
    keywords: [],
    affiliation: "Montana State University, USA",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/prakash-badu-43739923b/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Rajeev Ranjan Kumar",
    image: "Rajeev.png",
    degree: "M.Tech.",
    year: "2021 - 2023",
    researchTitle: "A Simplified Hyperbolic model for gas hydrate sediments",
    researchLink: "",
    email: "rajeev.kumar.14c@gmail.com",
    keywords: [],
    affiliation: "L&T energy and hydrocarbon",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/rajeev-ranjan-kumar-217a24a3/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Shabna Thasneem",
    image: "Shabna_2022.jpg",
    degree: "M.Tech.",
    year: "2020 - 2022",
    researchTitle:
      "Numerical modelling of 3D geo-reinforcement to quantify interfacial strength characteristics",
    researchLink: "",
    email: "shabnathasneem11@gmail.com",
    keywords: [],
    affiliation: "JGC India EPC Pvt Ltd",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/shabna-thasneem/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Rahul Ramachandran",
    image: "Rahul_2022.jpg",
    degree: "M.Tech.",
    year: "2020 - 2022",
    researchTitle:
      "Evolution of voids and constrictions during shearing granular materials",
    researchLink: "",
    email: "ce17b124@smail.iitm.ac.in",
    keywords: [],
    affiliation: "Winfra Technical Consultants",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink:
      "https://www.linkedin.com/in/rahul-ramachandran-4b3844190/?originalSubdomain=in",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Neeraj Pulaganti",
    image: "Neeraj_2021.png",
    degree: "M.Tech.",
    year: "2019 - 2021",
    researchTitle:
      "Quantification of constriction size distribution in porous media considering the effect of gradation and packing",
    researchLink: "",
    email: "neerajpulaganti141@gmail.com",
    keywords: [],
    affiliation: "Bauer Engineering India Private Limited",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/neeraj-pulaganti-37187a1bb/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Selvakumar N",
    image: "Selva_2020.png",
    degree: "M.Tech.",
    year: "2018 - 2020",
    researchTitle:
      "Particle migration studies of bentonite suspension through granular soils",
    researchLink: "",
    email: "selvakumar0410@gmail.com",
    keywords: [],
    affiliation: "Oil and Natural Gas Corporation (ONGC)",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/selvakumar--n/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Neeraj Keserwani",
    image: "Neeraj_2020.png",
    degree: "M.Tech.",
    year: "2018 - 2020",
    researchTitle:
      "Numerical analysis to determine pile load capacity for construction of Regional Rapid Transit System (RRTS) in NCR",
    researchLink: "",
    email: "neerajkeserwani78@gmail.com",
    keywords: [],
    affiliation: "Rail India Technical and Economic Service (RITES)",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "https://www.linkedin.com/in/neeraj-keserwani-92a6721b1/",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
];

export default function Alumni() {
  return (
    <>
      {alumniStudents.map((student, i) => (
        <StudentCard key={i} student={student} />
      ))}
    </>
  );
}
