import StudentCard from "../../../components/StudentCard/StudentCard";

// students.js
const alumniStudents = [
  {
    name: "Jithin S Kumar",
    image: "jsk.jpg",
    degree: "Ph.D.",
    year: "2019 - 2024",
    researchTitle:
      "Understanding the flow dynamics and deformation characteristics during fluid injection through porous media",
    researchLink: "",
    email: "jithin.jsk@gmail.com",
    keywords: [],
    affiliation: "ExxonMobil",
    googleSchLink:
      "https://scholar.google.co.in/citations?user=TcJS02cAAAAJ&hl=en",
    researchGateLink: "https://www.researchgate.net/profile/Jithin-Kumar-3",
    linkedinLink: "https://in.linkedin.com/in/jithin-s-kumar-090591b2",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Saikiran Naikoti",
    image: "SaiKiran.jpg",
    degree: "M.Tech.",
    year: "2022 - 2024",
    researchTitle:
      "Transition of cavity to finger during fluid injection through granular medium",
    researchLink: "",
    email: "naikotisaikiran22@gmail.com",
    keywords: [],
    affiliation: "Advanced Structural Engineering Consultants",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Megha S Narayanan",
    image: "Megha.jfif",
    degree: "M.Tech.",
    year: "2021 - 2023",
    researchTitle:
      "Numerical modelling of soil–coir geotextile interaction during pullout loading",
    researchLink: "",
    email: "megha19898@gmail.com",
    keywords: [],
    affiliation: "Hamburg University of Technology, Germany",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Prakash Badu",
    image: "Prakash.jpg",
    degree: "M.Tech.",
    year: "2021 - 2023",
    researchTitle:
      "Micromechanics of aggregate–rubber interactions during simple shear – A DEM study",
    researchLink: "",
    email: "prakash.badu123@gmail.com",
    keywords: [],
    affiliation: "Montana State University, USA",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Rajeev Ranjan Kumar",
    image: "Rajeev.png",
    degree: "M.Tech.",
    year: "2021 - 2023",
    researchTitle: "A Simplified Hyperbolic model for gas hydrate sediments",
    researchLink: "",
    email: "rajeev.kumar.14c@gmail.com",
    keywords: [],
    affiliation: "Prof. V. S. Raju Consultants",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Shabna Thasneem",
    image: "Shabna_2022.jpg",
    degree: "M.Tech.",
    year: "2020 - 2022",
    researchTitle:
      "Numerical modelling of 3D geo-reinforcement to quantify interfacial strength characteristics",
    researchLink: "",
    email: "shabnathasneem11@gmail.com",
    keywords: [],
    affiliation: "Larsen & Toubro Construction",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Rahul Ramachandran",
    image: "Rahul_2022.jpg",
    degree: "M.Tech.",
    year: "2020 - 2022",
    researchTitle:
      "Evolution of voids and constrictions during shearing granular materials",
    researchLink: "",
    email: "ce17b124@smail.iitm.ac.in",
    keywords: [],
    affiliation: "",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Neeraj Pulaganti",
    image: "Neeraj_2021.png",
    degree: "M.Tech.",
    year: "2019 - 2021",
    researchTitle:
      "Quantification of constriction size distribution in porous media considering the effect of gradation and packing",
    researchLink: "",
    email: "neerajpulaganti141@gmail.com",
    keywords: [],
    affiliation: "Bauer Engineering India Private Limited",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Selvakumar N",
    image: "Selva_2020.png",
    degree: "M.Tech.",
    year: "2018 - 2020",
    researchTitle:
      "Particle migration studies of bentonite suspension through granular soils",
    researchLink: "",
    email: "selvakumar0410@gmail.com",
    keywords: [],
    affiliation: "Oil and Natural Gas Corporation (ONGC)",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
  {
    name: "Neeraj Keserwani",
    image: "Neeraj_2020.png",
    degree: "M.Tech.",
    year: "2018 - 2020",
    researchTitle:
      "Numerical analysis to determine pile load capacity for construction of Regional Rapid Transit System (RRTS) in NCR",
    researchLink: "",
    email: "neerajkeserwani78@gmail.com",
    keywords: [],
    affiliation: "Rail India Technical and Economic Service (RITES)",
    googleSchLink: "",
    researchGateLink: "",
    linkedinLink: "",
    isPrimaryGuidePresent: false,
    guideName: "",
  },
];

export default function Alumni() {
  return (
    <>
      {alumniStudents.map((student, i) => (
        <StudentCard key={i} student={student} imageBasePath="alumni" />
      ))}
    </>
  );
}
